name: 'Import Self-Signing Keys'
description: 'imports the keys used to sign data in the key publishing repo'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: curl -L -o "${RUNNER_TEMP}/keys.run" https://arrjay.github.io/well-known-keys/install.run
    - shell: bash
      run: chmod +x "${RUNNER_TEMP}/keys.run"
    - shell: bash
      run: "\"${RUNNER_TEMP}/keys.run\" installersign-ownertrust 5"

