name: 'Import Self-Signing Keys'
description: 'imports the keys used to sign data in the key publishing repo'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: gpg --import .ci/self.asc
    - shell: bash
      run: gpg --import-ownertrust .ci/ownertrust
