# reusable job for installing the validation keys
on:
  workflow_call:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
        - run: |
            gpg --import .ci/self.asc
            gpg --import-ownertrust .ci/ownertrust
